spring:
  application:
    name: team07

  output:
    ansi:
      enabled: always

  #jpa
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

    ai:
      openai:
        api-key: ${OPENAI_API_KEY}
        chat:
          model: text-embedding-3-small
