spring:
  application:
    name: team07

  output:
    ansi:
      enabled: always

  profiles:
    group:
      local: "local"
      dev: "dev"
      test: "test"
    active: local

  #jpa
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  jackson:
    time-zone: Asia/Seoul

  config:
    import: optional:env[.env]
